name: chart-challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - geopandas
  - scikit-learn
  - ipywidgets
  - openpyxl
  - notebook
  - pip
  - pip:
      - kaleido  
